os: linux
dist: bionic

language: cpp
compiler: gcc-9

_install_qt: &install_qt
  before_install:
    - sudo apt-get install qt5-default
    - sudo apt-get install libgl1-mesa-dev

addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-9

jobs:
  include:
    - <<: *install_qt
      env: COMPILER_NAME=gcc CXX=g++-9 CC=gcc-9 BUILD_CONFIGURATION=Debug BUILD_GUI=ON
      branches:
        except:
          - master
          - console
          
    - env: COMPILER_NAME=gcc CXX=g++-9 CC=gcc-9 BUILD_CONFIGURATION=Debug BUILD_GUI=OFF
      branches:
        except:
          - master
          - GUI
          
    - <<: *install_qt
      env: COMPILER_NAME=gcc CXX=g++-9 CC=gcc-9 BUILD_CONFIGURATION=Release BUILD_GUI=ON
      branches:
        only: master
    
    - env: COMPILER_NAME=gcc CXX=g++-9 CC=gcc-9 BUILD_CONFIGURATION=Release BUILD_GUI=OFF
      branches:
        only: master
    
script:
- mkdir build
- cd build
- cmake -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION -DBUILD_GUI=$BUILD_GUI ..
- cmake --build .
- ctest --output-on-failure
