os: linux
dist: trusty

language: cpp
compiler: gcc-9

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-9

env: COMPILER_NAME=gcc CXX=g++-9 CC=gcc-9

script:
- mkdir build
- cd build
- cmake ..
- cmake --build .
- ctest --output-on-failure
